CREATE OR REPLACE FUNCTION kesplus_platform.header_option(option TEXT)
 RETURNS text
AS WRAPPED
XZ32wb2HGkq6tU6JSL4/yT3ZWaCiSsHPqNtCqXerzoabKFW4mknua+5zxJ57
l960QBjFl0zC1bHepIBp4KvR/ylxxiBskDzQghGmr6PAnbzuZ2F2xASmN+rz
kgjcnf2ZAHM8+zN0OyycbRaLtxnxuV6tWyA9CJJF5XfFI/Gig6IBASrAAUVz
OlcxiAaadHGvQ1eOKs60/ssi8tuW1amEWrlpI9Gdg1/vxUH+OcGWoKv6xdFI
9UtaoQPOZmJKjEe8pXoguPMBugxhwAyIEv6QRr9sZkJwfvNgUjeVaIcOZNQ=
END;

