CREATE OR REPLACE PACKAGE "public"."kcontext" AUTHID CURRENT_USER AS
    USER_ID VARCHAR;
    DEPT_ID VARCHAR;
    REGION integer;
    DEPT_IDS VARCHAR[];
    DIVISION_IDS VARCHAR[];
    MANAGE_DEPT_IDS VARCHAR[];
    MANAGE_REGIONS integer[];
    FUNCTION get_user_id() RETURN VARCHAR;
    FUNCTION get_dept_id() RETURN VARCHAR;
    FUNCTION get_dept_ids() RETURN VARCHAR[];
    FUNCTION get_division_ids() RETURN VARCHAR[];
    FUNCTION get_manage_ids() RETURN VARCHAR[];
    FUNCTION get_manage_regions() RETURN integer[];
END kcontext;

CREATE OR REPLACE PACKAGE BODY "public"."kcontext" AS WRAPPED
qA9PFdOh0rTbTuyiUlQqWGGZpV1tjHS5VV1Gmpmaaxnp60O/qClUOWMjBW7w
W875fHFGHdNYaIFAGIIAsmxUQJfddZZKqTlhbzI/js8vtKd3EcQ01XOjd8nF
8XcfPusjZVF98UL/naCoWvso0rr0slTGruht25S5PXmC82R/DBvTMEkZkCfE
SpN8FHV8I/ra9aKAte9P7vhOiI3YuRc8tyUOohSJFS0iLhHMDR0tIVyoD08V
06HStNtO7KJSVCpY/ans3+kv1jFGzmIRRTByh5Ns+MdBh5y+H2z6pg8YqH5a
p6HQqbU5lbrGvXz39OY5cXKMcFxO91wbD4EiFr5QzSd2DgbOBLQXy6GqCRw9
2Lw9V+GBHXSNiSMykf1FeMe31h0gM/PoumpnSegw00ue4zowKKSRkLu6I3qD
dSP/jAxN02eUBUQORzQY2wVKl0vtL6cSDjq9PujGOmObANIZIczJEs5+K9LT
yAcYM9zuPQbzRLZYdIGydIzrqSbKJa5Q1h0gM/PoumpnSegw00ue4zowKKSR
kLu6I3qDdSP/jAxN02eUBUQORzQY2wVKl0vtKvjqVfXUeMQxyAMWoUc6Xid2
DgbOBLQXy6GqCRw92Lzap8v17UxO6xASCvLfVNfyISoCmkBGqZLSzg1pr1fk
4gGoB7y1gXz8Nhf3yPkOXYi6/JZnNW1K2xdc8eJGuQbi7M92eNFOL5pAZpZt
ZD7GHvqjv5Zle4iDL4LSyZKaxxkLSwqxGsVKEr3t9YFlabq0wrbN/4O3mnWv
A4WopNJ5J+vhM8VepeK91VootzGXdWcqEMv/DHX6BKnjvxsGFo7/7xD/cXD2
1R80Yjrf0bgsujgvyGfxauOJB1TJjEK4yR0ya9N9TeYajlY82afS+fVJUzGu
stM8TgQkvtTX++Ko+A==
END;

